on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      - name: Build
        run: |
          bun install --frozen-lockfile
          bun run build
      - name: Check
        run: bun x biome check .
